name: nazgul

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: idaholab/moose-dev

    steps:
      - name: check dependencies
        shell: bash
        run: |
          if ! command -v g++ &> /dev/null
          then
            echo "g++ not found. Installing..."
            apt-get update
            apt-get install -y g++
          else
            COMPILER_VERSION=$(g++ --version | head -n1)
            echo "$COMPILER_VERSION is installed"
          fi
      - name: Install Google Test
        run: |
          sudo apt-get install -y cmake libgtest-dev
          cd /usr/src/gtest
          cmake .
          make -j $nproc

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          export PATH="/opt/libmesh/bin:$PATH"
          source /environment
          mkdir build
          cd build
          EIGEN3_ROOT=/opt/libmesh/include cmake ..
          make -j 8
          echo "Running tests inside the container"


      - name: Run Tests
        shell: bash
        run: |
          ./build/test/my_test
          
          

